### ISSUE TITLE
Dinosaur TODO

### ISSUE THREAD

**Issue by vsoch** [compspec/compspec#18]
## Software

- [ ] Refactor compspec here to accept plugins for compatibility extractors, checkers, etc.
  - [ ]  Different plugin types should match what I describe in my [Proposal D](https://github.com/opencontainers/wg-image-compatibility/pull/9)
  - [ ] The plugins should be discovered as other python modules with the same prefix (akin to what we did for snakemake)
  - [ ] Add in jsonschema (schema.py) to validate format
  - [ ] Each compatibility schema maintained by a community should still be kept separately. If a community or tool (e.g., IOR) makes a repository here, it can be stored alongside there (likely I'll do this for IOR)

## Visualization

- [ ] Write output formats for all the kinds of graphs I know about, so we can visualize!

## Example (ior)
 
- [ ] Write first prototype and examples with IOR
  - [ ] Then will have artifacts for IOR metadata, think about how to integrate into large graph for compatibility checking cases

**Comment by vsoch** [comment]
This issue is deprecated - the proposals are moving forward but (the extent to which we can follow them exactly) is not clear to me. Arguably, we are going to be making our own jobspec nextgen format for compatiility, and then use JGF, so I'm not sure any of this applies directly. Going to close for now until I rethink it.
